What is the diffreance between Numpy and List
Which one is faster.

In [9]:
heights = [74,75,72,71]

In [10]:
heights

[74, 75, 72, 71]

In [11]:
heights * 2.45

TypeError: can't multiply sequence by non-int of type 'float'

***To do above code we need to use the list compreancive or the for loop to do this like follows:***

In [15]:
# To do above code we need to use the list compreancive or the for loop to do this like follows:

l =[]
for i in heights:
    l.append(i*2.45)

In [14]:
l

[181.3, 183.75, 176.4, 173.95000000000002]

# So thats why numPy come in the picture:

In [2]:
import numpy as np

In [19]:
np_heights = np.array([74,75,72,71]) 

In [21]:
np_heights

array([74, 75, 72, 71])

In [23]:
type(np_heights)

numpy.ndarray

In [25]:
np_heights * 2.54

array([187.96, 190.5 , 182.88, 180.34])

##### So now the same thing can get achived through the numpy. In the form of numpy array

### NumPy comes with its own set of methods and operations

In [28]:
list_one = [1,2,3]
list_second = [4,5,6]

In [31]:
# Doing Concatination

list_one+list_second

[1, 2, 3, 4, 5, 6]

In [32]:
np_list_1 = np.array([1,2,3])
np_list_2 = np.array([4,5,6])

In [34]:
# doing addition in numPy
# The same + operator working deiffrently
np_list_1 + np_list_2

array([5, 7, 9])

***Working with N-D Array***

In [35]:
np_heights 

array([74, 75, 72, 71])

In [36]:
type(np_heights)

numpy.ndarray

In [3]:
test = np.array([range(0,10)])

In [6]:
np.array( [1.0, 2, 3.5, 0.2, "True"] )

array(['1.0', '2', '3.5', '0.2', 'True'], dtype='<U32')

In [11]:
np.array( [1.0, 2, 3.5, 0.2, True] )

array([1. , 2. , 3.5, 0.2, 1. ])

#### This is the correct answer. You have to provide the elements in the form of a list or a tuple to form an array. Also, a Boolean value is defined without the apostrophes.

In [9]:
np.array[1.0, 2, 3.5, 0.2, True]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [10]:
np.array(1.0, 2, 3.5, 0.2, True)

ValueError: only 2 non-keyword arguments accepted